language: c
compiler:
  - gcc
  - clang
before_install:
    - sudo apt-get -qq update
install:
    - sudo apt-get -qq install rake bison libcurl4-openssl-dev libhiredis-dev libmarkdown2-dev
env:
  - HTTPD_VERSION=httpd-2.4.9 
    APR=apr-1.5.1 
    APR_UTIL=apr-util-1.5.3 
    HTTPD_TAR=${HTTPD_VERSION}.tar.gz 
    APR_TAR=${APR}.tar.gz 
    APR_UTIL_TAR=${APR_UTIL}.tar.gz 
    HTTPD_CONFIG_OPT=
    APXS_CHECK_CMD="../${HTTPD_VERSION}/apache/bin/apachectl -v"
  - HTTPD_VERSION=httpd-2.2.27 
    APR=apr-1.5.1 
    APR_UTIL=apr-util-1.5.3 
    HTTPD_TAR=${HTTPD_VERSION}.tar.gz 
    APR_TAR=${APR}.tar.gz 
    APR_UTIL_TAR=${APR_UTIL}.tar.gz 
    HTTPD_CONFIG_OPT="--enable-module=all --enable-mods-shared=all"
    APXS_CHECK_CMD="../${HTTPD_VERSION}/apache/bin/apachectl -v"
before_script:
  - cd ../
  - wget http://ftp.jaist.ac.jp/pub/apache//httpd/${HTTPD_TAR}
  - tar xf ${HTTPD_TAR}
  - cd ${HTTPD_VERSION}/srclib
  - wget http://ftp.jaist.ac.jp/pub/apache//apr/${APR_TAR}
  - wget http://ftp.jaist.ac.jp/pub/apache//apr/${APR_UTIL_TAR}
  - tar xf ${APR_TAR}
  - tar xf ${APR_UTIL_TAR}
  - ln -s ${APR} apr
  - ln -s ${APR_UTIL} apr-util
  - cd ..
  - ./configure --prefix=`pwd`/apache --with-included-apr ${HTTPD_CONFIG_OPT}
  - make
  - make install
  - cd ../mod_mruby
script:
  - echo ${APXS_CHECK_CMD}
  - ${APXS_CHECK_CMD}
  - export APXS_PATH_ENV=--with-apxs=../${HTTPD_VERSION}/apache/bin/apxs
  - export APACHECTL_PATH_ENV=--with-apachectl=../${HTTPD_VERSION}/apache/bin/apachectl
  - sh test.sh
notifications:
  irc:
    channels:
      - "irc.freenode.org#hosting-ja"
    on_success: always
    on_failure: always
    use_notice: true
    skip_join: true
    template:
        - "[%{message}] %{repository} (%{commit}) by %{author}: See %{build_url}"
  webhooks:
    - secure: "BYpv6AjLGEtNMX67AaUEbirIQRX9Tl6ovPA/2+BDdHiNEMr1+xZVhp1rOBEP7nli1opvKe7OfJFNaJ2HRMmECmh3ZtfIiGQ8t3LtKd2kl+6tL9rdYuWo7M9PjGKsVXhcsJlK3FpeYXGGqmxRelapMAs+yn3EWz9S54Yy7QWqO/Q="

