language: c
compiler:
  - gcc
  - clang
before_install:
    - sudo apt-get -qq update
install:
    - sudo apt-get -qq install apache2 apache2-prefork-dev rake bison libcurl4-openssl-dev libhiredis-dev libmarkdown2-dev
before_script:
  - cd ../
  - wget http://ftp.jaist.ac.jp/pub/apache//httpd/httpd-2.4.9.tar.gz
  - tar xf httpd-2.4.9.tar.gz
  - cd httpd-2.4.9/srclib
  - wget http://ftp.jaist.ac.jp/pub/apache//apr/apr-1.5.0.tar.gz
  - wget http://ftp.jaist.ac.jp/pub/apache//apr/apr-util-1.5.3.tar.gz
  - tar xf apr-1.5.0.tar.gz
  - tar xf apr-util-1.5.3.tar.gz
  - ln -s apr-1.5.0 apr
  - ln -s apr-util-1.5.3 apr-util
  - cd ..
  - ./configure --prefix=`pwd`/apache --with-included-apr 
  - make
  - make install
  - cd ../mod_mruby
script: 
  # for 2.4.x using source installed binary
  - APXS_PATH_ENV='--with-apxs=../httpd-2.4.9/apache/bin/apxs' APACHECTL_PATH_ENV='--with-apachectl=../httpd-2.4.9/apache/bin/apachectl' sh build.sh
  # for 2.2.x using apt-get apache2 package
  - sh build.sh
notifications:
  irc:
    channels:
      - "irc.freenode.org#hosting-ja"
    on_success: always
    on_failure: always
    use_notice: true
    skip_join: true
    template:
        - "[%{message}] %{repository} (%{commit}) by %{author}: See %{build_url}"
  webhooks:
    - secure: "BYpv6AjLGEtNMX67AaUEbirIQRX9Tl6ovPA/2+BDdHiNEMr1+xZVhp1rOBEP7nli1opvKe7OfJFNaJ2HRMmECmh3ZtfIiGQ8t3LtKd2kl+6tL9rdYuWo7M9PjGKsVXhcsJlK3FpeYXGGqmxRelapMAs+yn3EWz9S54Yy7QWqO/Q="

