language: c
compiler:
  - gcc
before_script:
  - cd ../
  - wget http://ftp.kddilabs.jp/infosystems/apache//httpd/httpd-2.4.6.tar.gz
  - tar xvf httpd-2.4.6.tar.gz
  - cd httpd-2.4.6
  - ./configure --prefix=apache246 --enable-modules=all --enable-mods-shared=all --enable-mpms-shared='prefork worker event'
  - make
  - make install
  - cd ../mod_mruby
script: "APXS_PATH='../httpd-2.4.6/apache246/bin/apxs' APACHECTL_PATH='../httpd-2.4.6/apache246/bin/apachectl' sh build.sh"
