language: c
compiler:
  - gcc
  - clang
before_install:
    - sudo apt-get -qq update
    - sudo apt-get -qq install apache2 apache2-prefork-dev rake bison libcurl4-openssl-dev libhiredis-dev libmarkdown2-dev
before_script:
  - cd ../
  - wget http://ftp.kddilabs.jp/infosystems/apache//httpd/httpd-2.4.6.tar.gz
  - tar xf httpd-2.4.6.tar.gz
  - cd httpd-2.4.6/srclib
  - wget http://ftp.kddilabs.jp/infosystems/apache//apr/apr-1.4.8.tar.gz
  - wget http://ftp.kddilabs.jp/infosystems/apache//apr/apr-util-1.5.2.tar.gz
  - tar xf apr-1.4.8.tar.gz
  - tar xf apr-util-1.5.2.tar.gz
  - ln -s apr-1.4.8 apr
  - ln -s apr-util-1.5.2 apr-util
  - cd ..
  - ./configure --prefix=`pwd`/apache246 --with-included-apr 
  - make
  - make install
  - cd ../mod_mruby
script: 
  - APXS_PATH_ENV='../httpd-2.4.6/apache246/bin/apxs' APACHECTL_PATH_ENV='../httpd-2.4.6/apache246/bin/apachectl' sh build.sh
  - APXS_PATH_ENV='apxs' APACHECTL_PATH_ENV='apachectl' sh build.sh
notifications:
  irc:
    channels:
      - "irc.media.kyoto-u.ac.jp#mod_mruby"
    on_success: always
    on_failure: always
    template:
      - "%{message} by @%{author}: See %{build_url}"
